aliases:
    fleeks: cd ~/.local/share/fleek
bling: high
blocklist:
    - vscode
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - mold
    - zellij
    - nushell
    - clang
    - vulkan-loader
    - wayland
    - libxkbcommon
    - xorg.libX11
    - xorg.libXcursor
    - xorg.libXi
    - xorg.libXrandr
    - pkgconfig
    - udev
    - interception-tools
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: asustuf
      os: linux
      username: adamz
track: nixos-unstable
unfree: true
users:
    - email: zadroznyadam@pm.me
      name: Adam Zadrożny
      ssh_private_key_file: ~/.ssh/id_ed25519
      ssh_public_key_file: ~/.ssh/id_ed25519.pub
      username: adamz
